services:
  db:
    image: mysql:5.7
    container_name: mysql
    command: --wait_timeout=28800 --interactive_timeout=28800 --max_allowed_packet=64M
    env_file:
      - ../api/.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  db: