FROM node:20-alpine

WORKDIR /home/node/app

RUN apk update && apk upgrade && apk add --no-cache bash

COPY ../front/package.json ./
COPY ../front/package-lock.json ./

RUN npm install

COPY ../front .app